Add tests (#44)
* adding start to testing, needs a lot more work, just saving in case my computer explodes

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* adding tests for collection (still more to go!)

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* typo in config

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* adding all the tests!

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* rename container diff to not have extension

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* try moving to /usr/local/bin

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* adding container-diff to path

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* containerdiff version

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* try including Dockerfiles

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* need to include Dockerfile with tests

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* forgot to add Dockerfile"

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* mising http.server

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* python2 being used

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* ensure python3 being used

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* need to bump version

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* separate tests for python2/3

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* updating links to python 3

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

* version 2 deps

Signed-off-by: Vanessa Sochat <vsochat@stanford.edu>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3,7 +3,18 @@ version: 2.1
 orbs:
   # https://circleci.com/orbs/registry/orb/circleci/docker-publish
   docker-publish: circleci/docker-publish@0.1.3
+
 workflows:
+  test:
+    jobs:
+      - test-python-3:
+          filters:
+            branches:
+              ignore: docs/*
+      - test-python-2:
+          filters:
+            branches:
+              ignore: docs/*
 
   # This workflow will be run on all branches but master (to test)
   build_without_publishing_job:
@@ -48,3 +59,100 @@ workflows:
                    done
                    echo "Version for Docker tag is ${DOCKER_TAG}"
                    docker tag singularityhub/container-tree:latest singularityhub/container-tree:${DOCKER_TAG}
+
+
+
+install_containerdiff: &install_containerdiff
+  name: Install container-diff
+  command: |
+        if [ ! -x "$(which container-diff)" ] ; then
+            echo "Container diff not found on PATH! Downloading to /tmp"
+            curl -LO https://storage.googleapis.com/container-diff/latest/container-diff-linux-amd64
+            chmod +x container-diff-linux-amd64
+            mv container-diff-linux-amd64 $HOME/conda/bin/container-diff
+        fi
+        export PATH=$HOME/conda/bin:$PATH
+        echo "Container-Diff Installed"
+        container-diff version
+
+install: &install
+  name: install containertree
+  command: |
+     $HOME/conda/bin/pip uninstall containertree --yes || echo "Not installed"
+     $HOME/conda/bin/pip install .[all]
+
+
+install_python_3: &install_python_3
+  name: install Python 3.5 dependencies
+  command: | 
+      ls $HOME
+      if [ ! -d "/home/circleci/conda" ]; then
+          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
+          /bin/bash Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/conda
+          export PATH=$HOME/conda/bin:$PATH
+          $HOME/conda/bin/conda install pandas
+          $HOME/conda/bin/python setup.py install
+       else
+           echo "Miniconda 3 is already installed, continuing to build."
+       fi
+
+install_python_2: &install_python_2
+  name: install Python 3.5 dependencies
+  command: | 
+      ls $HOME
+      if [ ! -d "/home/circleci/conda" ]; then
+          wget https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh
+          /bin/bash Miniconda2-latest-Linux-x86_64.sh -b -p $HOME/conda
+          $HOME/conda/bin/conda install pandas
+          export PATH=$HOME/conda/bin:$PATH
+          $HOME/conda/bin/python setup.py install
+       else
+           echo "Miniconda 2 is already installed, continuing to build."
+       fi
+
+test_containertree: &test_containertree
+  name: Test Containertree
+  command: |
+        export PATH=$HOME/conda/bin:$PATH
+        python --version
+        cd ~/repo/containertree/tests
+        $HOME/conda/bin/python -m unittest test_utils
+        $HOME/conda/bin/python -m unittest test_collection
+        $HOME/conda/bin/python -m unittest test_container
+        $HOME/conda/bin/python -m unittest test_packages
+        /bin/bash test_client.sh
+
+jobs:
+  test-python-3:
+    machine: true
+    working_directory: ~/repo
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+          - v2-dependencies
+      - run: *install_python_3
+      - run: *install_containerdiff
+      - run: *install
+      - save_cache:
+          paths:
+            - /home/circleci/conda
+          key: v2-dependencies
+      - run: *test_containertree
+
+  test-python-2:
+    machine: true
+    working_directory: ~/repo
+    steps:
+      - checkout
+      - restore_cache:
+          keys:
+          - v2-dependencies
+      - run: *install_python_2
+      - run: *install_containerdiff
+      - run: *install
+      - save_cache:
+          paths:
+            - /home/circleci/conda
+          key: v2-dependencies        
+      - run: *test_containertree
